### ISSUE TITLE
Modal example generates exception: "Class 'TransitionEvent' has no instance getter 'relatedTarget'"

### ISSUE THREAD

**Issue by YuriKulaghin** [rikulo/bootjack#25]
I download github.com/rikulo/bootjack/archive/master.zip (v0.6.5+3) and run example/modal.html in the DartEditor-1.10.1 (Win7 and Linux) with the Preferences: Run and Debug: Break on exceptions: all. During the modal window opening and closing DartEditor breaks on the exception: "Class 'TransitionEvent' has no instance getter 'relatedTarget'" many times. How can I remove the reason of exception without changing of DartEditor preferences?

**Comment by jimmyshiau** [comment]
Fixed dquery, please run `pub upgrade` to upgrade to dquery 0.7.1+1.

**Comment by YuriKulaghin** [comment]
Thanks, Jimmy, it works!
