### ISSUE TITLE
Modal Class uses deprecated methods

### ISSUE THREAD

**Issue by bagulin** [rikulo/bootjack#29]
Class Modal uses method isDefaultPrevented  (https://github.com/rikulo/bootjack/blob/master/lib/src/modal.dart#L54) which is deprecated in dquery (see https://github.com/rikulo/dquery/commit/bd0b770f1fdcf2f5eb9fcc44d0eb39105eb6eb91#diff-045912301e58a414d7dc48dc3d034877)

**Comment by tomyeh** [comment]
Fixed
